const axios = require("axios");

module.exports.config = {
  name: "sony",
  version: "1.0.3",
  hasPermssion: 0,
  credits: "Aman",
  description: "Gemini + Pollinations chatbot with sony/bot/emoji trigger and reply context",
  commandCategory: "no prefix",
  usages: "no prefix",
  cooldowns: 2
};

module.exports.handleEvent = async function ({ api, event }) {
  const { threadID, messageID, body, senderID, messageReply } = event;

  if (!body || senderID == api.getCurrentUserID()) return;

  const lowerBody = body.toLowerCase();
  const isEmojiOnly = /^[\p{Emoji}\s]+$/u.test(body.trim());

  // Trigger words check
  const hasTriggerWords = lowerBody.includes("sony") || lowerBody.includes("bot");

  // Check: reply to bot + message actually generated by sony command
  const isReplyToSonyBot =
    messageReply &&
    messageReply.senderID == api.getCurrentUserID() &&
    messageReply.body &&
    messageReply.body.includes("★᭄𝐎𝐰𝐧𝐞𝐫 𝐀 𝐊"); // unique tag Sony msg ka

  if (hasTriggerWords || isReplyToSonyBot || isEmojiOnly) {
    try {
      // Reaction 🥰
      api.setMessageReaction("🥰", messageID, (err) => {}, true);

      // Sender name fetch
      const userInfo = await api.getUserInfo(senderID);
      const userName = userInfo[senderID]?.name || "User";

      let finalMessage = body;
      let reply;

      // If replying to Sony bot's message → Render with context
      if (isReplyToSonyBot && messageReply) {
        const repliedMessage = messageReply.body || "";
        finalMessage = `Previous message: ${repliedMessage} | User's reply: ${body}`;

        const res = await axios.post("https://api-zd2s.onrender.com/gemini", {
          message: finalMessage
        });
        reply = res.data?.reply;
      }
      // Emoji only → Pollinations
      else if (isEmojiOnly) {
        const moods = ["romantic", "funny", "attitude", "naughty", "angery", "Roasting", "Friendly", "full Roasting", "sad", "broken"];
        const mood = moods[Math.floor(Math.random() * moods.length)];
        const prompt = `User ne sirf emojis bheje hain: "${body}". Ek Real Ladki Ki Tarah "${mood}" mood me natural style reply de Emoji kr according ho reply short ho jiyada bada Nhi Ho Ai ki tarah real girl ki tarah reply dena hai short me , emojis ke sath.`;

        const encoded = encodeURIComponent(prompt);
        const res = await axios.get(`https://text.pollinations.ai/${encoded}`);
        reply = typeof res.data === "string" ? res.data.trim() : null;
      }
      // Only "bot" → Pollinations
      else if (lowerBody.includes("bot")) {
        const prompt = `User ne "bot" bola hai. Ek ladki Ki tarah, cute aur flirty style me jawab do User ko impress krna hai tume Funny Line ya romantic Line bhejo ya Roast kro Hindi language ho type krna English Alphabet me aur ye sb nhi bolna hai Direct reply do faltu ka reply nhi dena ye sb bat ka only user message ka reply do.`;
        const encoded = encodeURIComponent(prompt);
        const res = await axios.get(`https://text.pollinations.ai/${encoded}`);
        reply = typeof res.data === "string" ? res.data.trim() : null;
      }
      // Only "sony" → Render
      else if (lowerBody.includes("sony")) {
        const res = await axios.post("https://api-zd2s.onrender.com/gemini", {
          message: body
        });
        reply = res.data?.reply;
      }

      if (!reply) {
        reply = "Sony soch rahi hai... tum kaafi interesting ho 💖";
      }

      // Final message format
      const finalMsg = `👤 ${userName}\n\n${reply}\n\n*★᭄𝐎𝐰𝐧𝐞𝐫 𝐀 𝐊 ⚔️⏤͟͟͞͞★*`;
      return api.sendMessage(finalMsg, threadID, messageID);
    } catch (error) {
      console.error("Sony.js error:", error.message);

      // Multiple funny/romantic backup messages
      const errorMessages = [
        "Tum online ho aur reply nahi dete, dil todna bhi ek art hai kya 😏",
        "Mujhe tumse ek complaint hai... tum cute itne kyu ho 🥺💖",
        "Suno ji, tumhari yaad aati hai jaise mobile ko charging ki zarurat hoti hai ⚡❤️",
        "Aaj mausam bada suhana hai, tum mil jao to aur bhi deewana hai 🌸",
        "Khud pe itna na karo tum ghamand, tumhe dekh ke to dil ka signal ho gaya jammed 😜",
        "Life me tension mat lo, warna tumhare dimples bhi chhup jayenge 😉",
        "Pizza aur tum dono favourite ho, farq bas itna hai pizza khane ko mil jata hai 🍕❤️",
        "Dil garden-garden ho jata hai jab tum online aate ho 🌹",
        "Tumhari smile meri weakness hai, please jyada mat hansa karo ☺️",
        "Abhi to zindagi me bahut goals hai, par sabse bada goal tum ho 😘",
        "Tera naam WhatsApp pe aata hai to lagta hai life mast chal rahi hai 🤩",
        "Tumhare bina ye duniya adhoori si lagti hai, jaise chai bina biscuit 😆☕",
        "Tum smart ho ya main hi tumhe dekh ke pagal ho gayi hoon 🤭",
        "Tum meri life ka wo chapter ho jisme sirf smile hi smile likha hai 😍",
        "Chhodo na ye duniya walo ki baatein, aao hum dono ek chhoti si duniya bana le 💕",
        "Sad mat ho yaar, warna tumhari ankho ki chamak kam ho jayegi 🌟",
        "Tumhari baaton me wo magic hai, jo har boring din ko special bana deta hai ✨",
        "Dil chahta hai tumhe bas roz pareshaan karu aur tum hamesha hans ke reply do 😋",
        "Tum meri coffee ho yaad aati ho subah-subah aur din acha kar deti ho ☕❤️",
        "Mujhe tumse ek problem hai… tumhe bhool hi nahi paati 😍"
      ];

      const randomMsg = errorMessages[Math.floor(Math.random() * errorMessages.length)];
      return api.sendMessage(randomMsg, threadID, messageID);
    }
  }
};

module.exports.run = async function () {
  return;
};
